# Generated by Django 4.2.4 on 2023-08-10 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realtors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="photos/%Y/%m/%d")),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(max_length=20)),
                ("top_seller", models.BooleanField(default=False)),
                (
                    "date_hired",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
