# Generated by Django 4.2.4 on 2023-08-10 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Realtors",
            new_name="Realtor",
        ),
    ]
